export const contents = [
  {
    boardId: 25,
    boardWriter: "저자입니다",
    boardTitle: "타이틀입니다",
    boardContent: "내용입니다",
    boardDate: "2024-07-18 06:02:24.164",
    boardIsBanned: false,
    boardIsDelete: false,
    boardHit: 0,
    boardScore: 0,
    boardRegion: null,
  },
  {
    boardId: 24,
    boardWriter: "저자입니다",
    boardTitle: "타이틀입니다",
    boardContent: "내용입니다",
    boardDate: "2024-07-18 06:02:07.039",
    boardIsBanned: false,
    boardIsDelete: false,
    boardHit: 0,
    boardScore: 0,
    boardRegion: {
      regionId: "1111010900",
      regionSido: "서울특별시",
      regionGugun: "종로구",
      regionDong: "누상동",
    },
  },
  {
    boardId: 23,
    boardWriter: "저자입니다",
    boardTitle: "타이틀입니다",
    boardContent: "내용입니다",
    boardDate: "2024-07-18 06:01:58.338",
    boardIsBanned: false,
    boardIsDelete: false,
    boardHit: 0,
    boardScore: 0,
    boardRegion: null,
  },
  {
    boardId: 22,
    boardWriter: "저자입니다",
    boardTitle: "타이틀입니다",
    boardContent: "내용입니다",
    boardDate: "2024-07-18 05:46:14.165",
    boardIsBanned: false,
    boardIsDelete: false,
    boardHit: 0,
    boardScore: 0,
    boardRegion: null,
  },
  {
    boardId: 21,
    boardWriter: "저자입니다",
    boardTitle: "타이틀입니다",
    boardContent: "내용입니다",
    boardDate: "2024-07-18 05:46:07.683",
    boardIsBanned: false,
    boardIsDelete: false,
    boardHit: 0,
    boardScore: 0,
    boardRegion: {
      regionId: "1111010900",
      regionSido: "서울특별시",
      regionGugun: "종로구",
      regionDong: "누상동",
    },
  },
  {
    boardId: 20,
    boardWriter: "저자입니다",
    boardTitle: "타이틀입니다",
    boardContent: "내용입니다",
    boardDate: "2024-07-18 05:40:20.557",
    boardIsBanned: false,
    boardIsDelete: false,
    boardHit: 0,
    boardScore: 0,
    boardRegion: {
      regionId: "1111010900",
      regionSido: "서울특별시",
      regionGugun: "종로구",
      regionDong: "누상동",
    },
  },
  {
    boardId: 19,
    boardWriter: "저자입니다",
    boardTitle: "타이틀입니다",
    boardContent: "내용입니다",
    boardDate: "2024-07-18 05:39:49.158",
    boardIsBanned: false,
    boardIsDelete: false,
    boardHit: 0,
    boardScore: 0,
    boardRegion: null,
  },
  {
    boardId: 18,
    boardWriter: "저자입니다",
    boardTitle: "타이틀입니다",
    boardContent: "내용입니다",
    boardDate: "2024-07-18 05:34:45.333",
    boardIsBanned: false,
    boardIsDelete: false,
    boardHit: 0,
    boardScore: 0,
    boardRegion: {
      regionId: "1111010900",
      regionSido: "서울특별시",
      regionGugun: "종로구",
      regionDong: "누상동",
    },
  },
  {
    boardId: 17,
    boardWriter: "저자입니다",
    boardTitle: "타이틀입니다",
    boardContent: "내용입니다",
    boardDate: "2024-07-18 05:34:01.800",
    boardIsBanned: false,
    boardIsDelete: false,
    boardHit: 0,
    boardScore: 0,
    boardRegion: {
      regionId: "1111010900",
      regionSido: "서울특별시",
      regionGugun: "종로구",
      regionDong: "누상동",
    },
  },
  {
    boardId: 16,
    boardWriter: "저자입니다",
    boardTitle: "타이틀입니다",
    boardContent: "내용입니다",
    boardDate: "2024-07-18 05:33:39.845",
    boardIsBanned: false,
    boardIsDelete: false,
    boardHit: 0,
    boardScore: 0,
    boardRegion: null,
  },
  {
    boardId: 15,
    boardWriter: "저자입니다",
    boardTitle: "타이틀입니다",
    boardContent: "내용입니다",
    boardDate: "2024-07-18 05:33:08.694",
    boardIsBanned: false,
    boardIsDelete: false,
    boardHit: 0,
    boardScore: 0,
    boardRegion: null,
  },
  {
    boardId: 14,
    boardWriter: "저자입니다",
    boardTitle: "타이틀입니다",
    boardContent: "내용입니다",
    boardDate: "2024-07-18 05:32:42.404",
    boardIsBanned: false,
    boardIsDelete: false,
    boardHit: 0,
    boardScore: 0,
    boardRegion: null,
  },
  {
    boardId: 13,
    boardWriter: "저자입니다",
    boardTitle: "타이틀입니다",
    boardContent: "내용입니다",
    boardDate: "2024-07-18 05:29:44.452",
    boardIsBanned: false,
    boardIsDelete: false,
    boardHit: 0,
    boardScore: 0,
    boardRegion: null,
  },
  {
    boardId: 12,
    boardWriter: "저자입니다",
    boardTitle: "타이틀입니다",
    boardContent: "내용입니다",
    boardDate: "2024-07-18 05:29:14.037",
    boardIsBanned: false,
    boardIsDelete: false,
    boardHit: 0,
    boardScore: 0,
    boardRegion: null,
  },
  {
    boardId: 11,
    boardWriter: "저자입니다",
    boardTitle: "타이틀입니다",
    boardContent: "내용입니다",
    boardDate: "2024-07-18 05:26:42.897",
    boardIsBanned: false,
    boardIsDelete: false,
    boardHit: 0,
    boardScore: 0,
    boardRegion: null,
  },
  {
    boardId: 10,
    boardWriter: "저자입니다",
    boardTitle: "타이틀입니다",
    boardContent: "내용입니다",
    boardDate: "2024-07-18 05:25:19.814",
    boardIsBanned: false,
    boardIsDelete: false,
    boardHit: 0,
    boardScore: 0,
    boardRegion: null,
  },
  {
    boardId: 9,
    boardWriter: "저자입니다",
    boardTitle: "타이틀입니다",
    boardContent: "내용입니다",
    boardDate: "2024-07-18 05:24:47.252",
    boardIsBanned: false,
    boardIsDelete: false,
    boardHit: 0,
    boardScore: 0,
    boardRegion: null,
  },
  {
    boardId: 8,
    boardWriter: "저자입니다",
    boardTitle: "타이틀입니다",
    boardContent: "내용입니다",
    boardDate: "2024-07-18 05:24:16.137",
    boardIsBanned: false,
    boardIsDelete: false,
    boardHit: 0,
    boardScore: 0,
    boardRegion: null,
  },
  {
    boardId: 7,
    boardWriter: "저자입니다",
    boardTitle: "타이틀입니다",
    boardContent: "내용입니다",
    boardDate: "2024-07-18 05:22:37.065",
    boardIsBanned: false,
    boardIsDelete: false,
    boardHit: 0,
    boardScore: 0,
    boardRegion: null,
  },
  {
    boardId: 6,
    boardWriter: "저자입니다",
    boardTitle: "타이틀 수정",
    boardContent: "내용입니다",
    boardDate: "2024-07-18 05:15:55.591",
    boardIsBanned: false,
    boardIsDelete: false,
    boardHit: 0,
    boardScore: 0,
    boardRegion: {
      regionId: "11110111",
      regionSido: "서울특별시",
      regionGugun: "종로구",
      regionDong: "옥인동",
    },
  },
  {
    boardId: 5,
    boardWriter: "저자입니다",
    boardTitle: "타이틀입니다",
    boardContent: "내용입니다",
    boardDate: "2024-07-18 04:56:18.933",
    boardIsBanned: false,
    boardIsDelete: false,
    boardHit: 0,
    boardScore: 0,
    boardRegion: null,
  },
  {
    boardId: 4,
    boardWriter: "저자입니다",
    boardTitle: "타이틀입니다",
    boardContent: "내용입니다",
    boardDate: "2024-07-18 04:54:36.719",
    boardIsBanned: false,
    boardIsDelete: false,
    boardHit: 0,
    boardScore: 0,
    boardRegion: null,
  },
  {
    boardId: 3,
    boardWriter: "저자입니다",
    boardTitle: "타이틀 수정",
    boardContent: "내용입니다",
    boardDate: "2024-07-18 04:54:18.012",
    boardIsBanned: false,
    boardIsDelete: false,
    boardHit: 0,
    boardScore: 0,
    boardRegion: null,
  },
  {
    boardId: 2,
    boardWriter: "저자입니다",
    boardTitle: "타이틀입니다",
    boardContent: "내용입니다",
    boardDate: "2024-07-18 04:53:40.737",
    boardIsBanned: false,
    boardIsDelete: false,
    boardHit: 0,
    boardScore: 0,
    boardRegion: null,
  },
  {
    boardId: 1,
    boardWriter: "저자입니다",
    boardTitle: "타이틀입니다",
    boardContent: "내용입니다",
    boardDate: "2024-07-18 04:53:40.737",
    boardIsBanned: false,
    boardIsDelete: false,
    boardHit: 0,
    boardScore: 0,
    boardRegion: null,
  },
];

export const products = [
  {
    message: "success",
    data: {
      lat: 37.5,
      lng: 127,
      productId: 1,
      productType: "ONEROOM",
      productAddress: "147-51",
      productDeposit: 1000,
      productRent: 20,
      productMaintenance: 5,
      productMaintenanceInfo: "수도세 포함, 전기세 미포함",
      productIsRentSupportable: true,
      productIsFurnitureSupportable: true,
      productSquare: 44.55,
      productRoom: 2,
      productOption: "1111111",
      productAdditionalOption: ["전자레인지", "의자"],
      productIsBanned: false,
      productIsDeleted: false,
      productPostDate: "2024-07-19 04:01:15.256",
      productStartDate: "2024-08-01",
      productEndDate: "2024-12-30",
      boardRegion: {
        regionId: "1111010900",
        regionSido: "서울특별시",
        regionGugun: "종로구",
        regionDong: "누상동",
      },
    },
    status: "OK",
  },
  {
    message: "success",
    data: {
      lat: 37.5,
      lng: 127,
      productId: 2,
      productType: "ONEROOM",
      productAddress: "147-51",
      productDeposit: 500,
      productRent: 30,
      productMaintenance: 10,
      productMaintenanceInfo: "수도세 포함, 전기세 미포함",
      productIsRentSupportable: true,
      productIsFurnitureSupportable: true,
      productSquare: 44.55,
      productRoom: 2,
      productOption: "1111111",
      productAdditionalOption: ["전자레인지", "책상"],
      productIsBanned: false,
      productIsDeleted: false,
      productPostDate: "2024-07-19 04:01:15.256",
      productStartDate: "2024-08-01",
      productEndDate: "2024-12-30",
      boardRegion: {
        regionId: "1111010900",
        regionSido: "대구광역시",
        regionGugun: "달서구",
        regionDong: "진천동",
      },
    },
    status: "OK",
  },
  {
    message: "success",
    data: {
      lat: 37.5,
      lng: 127,
      productId: 3,
      productType: "OPISTEL",
      productAddress: "147-51",
      productDeposit: 300,
      productRent: 100,
      productMaintenance: 7,
      productMaintenanceInfo: "수도세 포함, 전기세 미포함",
      productIsRentSupportable: true,
      productIsFurnitureSupportable: true,
      productSquare: 44.55,
      productRoom: 2,
      productOption: "1111001",
      productAdditionalOption: [],
      productIsBanned: false,
      productIsDeleted: false,
      productPostDate: "2024-07-19 04:01:15.256",
      productStartDate: "2024-08-01",
      productEndDate: "2024-12-30",
      boardRegion: {
        regionId: "1111010900",
        regionSido: "경상북도",
        regionGugun: "구미시",
        regionDong: "황상동",
      },
    },
    status: "OK",
  },
  {
    message: "success",
    data: {
      lat: 37.5,
      lng: 127,
      productId: 4,
      productType: "TWOROOM",
      productAddress: "147-51",
      productDeposit: 1000,
      productRent: 10,
      productMaintenance: 7,
      productMaintenanceInfo: "수도세 포함, 전기세 미포함",
      productIsRentSupportable: true,
      productIsFurnitureSupportable: true,
      productSquare: 44.55,
      productRoom: 2,
      productOption: "1101011",
      productAdditionalOption: ["전자레인지"],
      productIsBanned: false,
      productIsDeleted: false,
      productPostDate: "2024-07-19 04:01:15.256",
      productStartDate: "2024-08-01",
      productEndDate: "2024-12-30",
      boardRegion: {
        regionId: "1111010900",
        regionSido: "경기도",
        regionGugun: "파주시",
        regionDong: "야당동",
      },
    },
    status: "OK",
  },
  {
    message: "success",
    data: {
      lat: 37.5,
      lng: 127,
      productId: 5,
      productType: "ONEROOM",
      productAddress: "147-51",
      productDeposit: 1000,
      productRent: 5,
      productMaintenance: 8,
      productMaintenanceInfo: "수도세 포함, 전기세 미포함",
      productIsRentSupportable: true,
      productIsFurnitureSupportable: true,
      productSquare: 44.55,
      productRoom: 2,
      productOption: "0110011",
      productAdditionalOption: ["전자레인지"],
      productIsBanned: false,
      productIsDeleted: false,
      productPostDate: "2024-07-19 04:01:15.256",
      productStartDate: "2024-08-01",
      productEndDate: "2024-12-30",
      boardRegion: {
        regionId: "1111010900",
        regionSido: "대구광역시",
        regionGugun: "중구",
        regionDong: "교동",
      },
    },
    status: "OK",
  },
];

export const usersFavItems = [
  {
    message: "success",
    data: {
      lat: 37.5,
      lng: 127,
      productId: 4,
      productType: "TWOROOM",
      productAddress: "147-51",
      productDeposit: 1000,
      productRent: 10,
      productMaintenance: 7,
      productMaintenanceInfo: "수도세 포함, 전기세 미포함",
      productIsRentSupportable: true,
      productIsFurnitureSupportable: true,
      productSquare: 44.55,
      productRoom: 2,
      productOption: "1101011",
      productAdditionalOption: ["전자레인지"],
      productIsBanned: false,
      productIsDeleted: false,
      productPostDate: "2024-07-19 04:01:15.256",
      productStartDate: "2024-08-01",
      productEndDate: "2024-12-30",
      boardRegion: {
        regionId: "1111010900",
        regionSido: "경기도",
        regionGugun: "파주시",
        regionDong: "야당동",
      },
    },
    status: "OK",
  },
  {
    message: "success",
    data: {
      lat: 37.5,
      lng: 127,
      productId: 5,
      productType: "ONEROOM",
      productAddress: "147-51",
      productDeposit: 1000,
      productRent: 5,
      productMaintenance: 8,
      productMaintenanceInfo: "수도세 포함, 전기세 미포함",
      productIsRentSupportable: true,
      productIsFurnitureSupportable: true,
      productSquare: 44.55,
      productRoom: 2,
      productOption: "0110011",
      productAdditionalOption: ["전자레인지"],
      productIsBanned: false,
      productIsDeleted: false,
      productPostDate: "2024-07-19 04:01:15.256",
      productStartDate: "2024-08-01",
      productEndDate: "2024-12-30",
      boardRegion: {
        regionId: "1111010900",
        regionSido: "대구광역시",
        regionGugun: "중구",
        regionDong: "교동",
      },
    },
    status: "OK",
  },
];

export const users = [
  {
    userId: 1,
    userName: "관리자",
    userEmail: "admin",
    userPassword:
      "$2a$10$MNNHcEgr87FToesQypInQOAtJmNmX8TqwNQYJ1wMbvRl5i.XcXeOm",
    userBirthYear: 1998,
    userPhone: "010",
    userRegisterDate: "2024-07-19 13:41:30.857",
    userNickname: "어드민",
    userGender: 0,
    userSso: "NAVER",
    userIsAdmin: true,
    userIsDeleted: false,
    userIsBanned: false,
  },
];
