export const resData = {
  message: "SUCCESS",
  board: {
    boardId: 1,
    boardTitle: "타이틀",
    boardContent: "asdfsadf",
    boardDate: "2024-07-22 11:24:16.017",
    boardIsBanned: false,
    boardIsDelete: false,
    boardHit: 0,
    boardScore: 0,
    boardRegion: null,
    boardComment: [
      {
        commentId: 1,
        commentContent: "첫번째 댓글",
        commentUser: {
          userId: 1,
          userName: "관리자",
          userEmail: "admin",
          userPassword:
            "$2a$10$MNNHcEgr87FToesQypInQOAtJmNmX8TqwNQYJ1wMbvRl5i.XcXeOm",
          userBirthYear: 1998,
          userPhone: "010",
          userRegisterDate: "2024-07-19 13:41:30.857",
          userNickname: "어드민",
          userGender: 0,
          userSso: "NAVER",
          userIsAdmin: true,
          userIsDeleted: false,
          userIsBanned: false,
        },
        comments: [],
        commentDate: "2024-07-22T11:25:16.906+00:00",
        commentIsDeleted: false,
      },
      {
        commentId: 2,
        commentContent: "두번째 댓글",
        commentUser: {
          userId: 2,
          userName: "일반",
          userEmail: "user",
          userPassword:
            "$2a$10$HJFwab/8RwivR7Fr3Q4rM.J3eCZEPsxKijNqMpaV09zOA4eqEZPFe",
          userBirthYear: 1998,
          userPhone: "010",
          userRegisterDate: "2024-07-19 13:41:35.067",
          userNickname: "유저",
          userGender: 1,
          userSso: "GOOGLE",
          userIsAdmin: false,
          userIsDeleted: false,
          userIsBanned: false,
        },
        comments: [
          {
            commentId: 3,
            commentContent: "asdfasdfasdf",
            commentUser: {
              userId: 2,
              userName: "일반",
              userEmail: "user",
              userPassword:
                "$2a$10$HJFwab/8RwivR7Fr3Q4rM.J3eCZEPsxKijNqMpaV09zOA4eqEZPFe",
              userBirthYear: 1998,
              userPhone: "010",
              userRegisterDate: "2024-07-19 13:41:35.067",
              userNickname: "유저",
              userGender: 1,
              userSso: "GOOGLE",
              userIsAdmin: false,
              userIsDeleted: false,
              userIsBanned: false,
            },
            comments: [
              {
                commentId: 8,
                commentContent: "두번째 댓글",
                commentUser: {
                  userId: 1,
                  userName: "관리자",
                  userEmail: "admin",
                  userPassword:
                    "$2a$10$MNNHcEgr87FToesQypInQOAtJmNmX8TqwNQYJ1wMbvRl5i.XcXeOm",
                  userBirthYear: 1998,
                  userPhone: "010",
                  userRegisterDate: "2024-07-19 13:41:30.857",
                  userNickname: "어드민",
                  userGender: 0,
                  userSso: "NAVER",
                  userIsAdmin: true,
                  userIsDeleted: false,
                  userIsBanned: false,
                },
                comments: [],
                commentDate: "2024-07-22T11:27:49.599+00:00",
                commentIsDeleted: false,
              },
            ],
            commentDate: "2024-07-22T11:26:25.397+00:00",
            commentIsDeleted: false,
          },
          {
            commentId: 4,
            commentContent: "asdfasdfasdf",
            commentUser: {
              userId: 1,
              userName: "관리자",
              userEmail: "admin",
              userPassword:
                "$2a$10$MNNHcEgr87FToesQypInQOAtJmNmX8TqwNQYJ1wMbvRl5i.XcXeOm",
              userBirthYear: 1998,
              userPhone: "010",
              userRegisterDate: "2024-07-19 13:41:30.857",
              userNickname: "어드민",
              userGender: 0,
              userSso: "NAVER",
              userIsAdmin: true,
              userIsDeleted: false,
              userIsBanned: false,
            },
            comments: [],
            commentDate: "2024-07-22T11:26:28.972+00:00",
            commentIsDeleted: false,
          },
        ],
        commentDate: "2024-07-22T11:25:52.745+00:00",
        commentIsDeleted: false,
      },
      {
        commentId: 5,
        commentContent: "세번째 댓글",
        commentUser: {
          userId: 1,
          userName: "관리자",
          userEmail: "admin",
          userPassword:
            "$2a$10$MNNHcEgr87FToesQypInQOAtJmNmX8TqwNQYJ1wMbvRl5i.XcXeOm",
          userBirthYear: 1998,
          userPhone: "010",
          userRegisterDate: "2024-07-19 13:41:30.857",
          userNickname: "어드민",
          userGender: 0,
          userSso: "NAVER",
          userIsAdmin: true,
          userIsDeleted: false,
          userIsBanned: false,
        },
        comments: [],
        commentDate: "2024-07-22T11:26:51.986+00:00",
        commentIsDeleted: false,
      },
    ],
    boardWriter: {
      userId: 1,
      userName: "관리자",
      userEmail: "admin",
      userPassword:
        "$2a$10$MNNHcEgr87FToesQypInQOAtJmNmX8TqwNQYJ1wMbvRl5i.XcXeOm",
      userBirthYear: 1998,
      userPhone: "010",
      userRegisterDate: "2024-07-19 13:41:30.857",
      userNickname: "어드민",
      userGender: 0,
      userSso: "NAVER",
      userIsAdmin: true,
      userIsDeleted: false,
      userIsBanned: false,
    },
  },
  status: 200,
};
