services:
  front:
    build:
      context: ./bangtong/front
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - back

  back:
    build:
      context: ./bangtong/back
      dockerfile: Dockerfile
    ports:
      - 8080:8080
