services:
  bangtong-front:
    container_name: prod-bangtong-front
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_NAME=bangtong
        - REACT_APP_TITLE=방통터치
    ports:
      - 8000:80