FROM node:lts-alpine AS build
LABEL MAINTAINER="Seoryeong Min(msr980929@gmail.com)"

WORKDIR /usr/src/app
COPY package.json .
RUN npm install
COPY . .

ARG REACT_APP_NAME
ENV REACT_APP_NAME=${REACT_APP_NAME}
ARG REACT_APP_TITLE
ENV REACT_APP_TITLE=${REACT_APP_TITLE}
RUN npm run build

FROM nginx
COPY --from=build /usr/src/app/build /usr/share/nginx/html
